### PR TITLE
Use lastRowAtIndex for the last row

### PR DESCRIPTION
**Pull request by giiiita**
`// Dirty little hack to handle layouting of the last row gracefully :`
I tried to improve this.

### CODE REVIEW

**Review by karolkulesza — CHANGES_REQUESTED** [review]
Nice improvement!
However, I think some small adjustments would be nice, to avoid code duplication that we'll end up with, if I approve this PR in this form. `rowAtIndex` and `lastRowAtIndex` functions would have quite a lot of common code, so I would suggest to combine them into one function and use conditional statements. Also `contentAtIndex` function after those changes should be also adjusted (with the comment as well), maybe even deleted.

**Comment by giiiita** [comment]
Thank you for the review!
Combined into one function!

**Comment by karolkulesza** [comment]
Thanks for the changes!
Merging, I’ll just remove the `contentCount` param and one condition in `rowAtIndex` func, as they’re unnecessary. Thank you👍

**Comment by giiiita** [comment]
`ForEach((0..<(isLastRow ? data.count % cols : cols))`

Thank you for a good clean!!!

**Pull request merged**
