### PR TITLE
Added property isScrollable to allow QGrid to work in parent ScrollViews

### PR DESCRIPTION
**Pull request by kenmueller**
I've added an `isScrollable` property since I'm using a QGrid in an app I'm working on, but it won't work in a parent ScrollView.

### CODE REVIEW

**Comment by karolkulesza** [comment]
Thanks for contributing.

Could you please remove *.xcuserdatad files from this PR? I believe they shouldn't be part of the commits.

Also, I can see you've modified some default existing values for the `QGrid` initializer. Please revert that, if possible.

**Comment by kenmueller** [comment]
Sure, working on it now. The initial values tripped me up a ton in the beginning because I feel like it's very odd to have a default value that is not 0 for the padding.

**Comment by bryanbartow** [comment]
@kenmueller Any update on this? I'm happy to make my own PR if you're too busy.

**Comment by bryanbartow** [comment]
@karolkulesza I opened my own PR in case @kenmueller is unable to get to this soon. #28

**Comment by karolkulesza** [comment]
Closing, as @bryanbartow's PR with this change has been just merged.

**Pull request closed without merging**
